name: Build Windows MSI

on:
  push:
    branches: [ main, master, "*" ]
  workflow_dispatch: {}

jobs:
  build-windows-msi:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r MiniFileBot/requirements.txt pyinstaller

      - name: Build EXE (PyInstaller)
        shell: cmd
        working-directory: MiniFileBot
        run: |
          pyinstaller --noconfirm --clean --windowed --onefile app_gui.py ^
            --name MiniFileBot ^
            --collect-all PySide6 ^
            --collect-submodules guessit
          copy config.yaml dist\config.yaml

      - name: Install WiX Toolset (for MSI)
        run: choco install wixtoolset --yes

      - name: Build MSI (WiX)
        shell: cmd
        working-directory: installer
        run: |
          if not exist ..\dist mkdir ..\dist
          set BUILDOUT=%CD%\..\MiniFileBot\dist
          candle.exe -dBuildOutput="%BUILDOUT%" MiniFileBot.wxs -o MiniFileBot.wixobj
          light.exe MiniFileBot.wixobj -ext WixUIExtension -o ..\dist\MiniFileBot-Installer.msi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MiniFileBot-MSI
          path: dist/
